27.8.23

diff --git a/mountcopy b/mountcopy
--- a/mountcopy
+++ b/mountcopy
@@ -5,29 +5,49 @@ export PATH=/bin:/usr/bin
 
 # CONSTANTS
 PATTERN="*.gcode"
-DESTINATION="/home/pi/printer_data/gcodes"
+
+# For Raspberry Pi use 
+#DESTINATION="/home/pi/printer_data/gcodes"
+
+# For BIQU CB 1 modul use
+DESTINATION="/home/biqu/printer_data/gcodes" 
+# =========
 
 
-# The block device name is expected to be passed as the first argumet.
+# The block device name is expected to be passed as the first argument.
 device="$1"
 
 if [ -z "$device" ]; then
-    echo "Missing block device name!"
+    echo "Missing block device name!" >>/tmp/mountcopy.log
     exit 1
 fi
 
 # Temporary directory where we will mount the filesystem
 mnt=$(mktemp -d)
+# Strange error codes are for debugging purposes.
+# Mount device into filesystem at $destination.
+mount "/dev/$device" "$mnt" 2>>/tmp/mountcopy.log || exit 106
 
 # The copied files will belong to root, but we will grant all permissions to other users.
 umask 0111
 
-# Strange error codes are for debugging purpouses.
-# Mount device into filesystem at $destination.
-mount -r "/dev/$device" "$mnt" || exit 101
-# Copy files fitting $PATTERN from the root of the drive to $DESTINATION.
-cp $(echo "$mnt/$PATTERN") "$DESTINATION/" || exit 102
+# Clean log file
+echo "" > /tmp/mountcopy.log
+# Determine wither we should export or import files
+if [ -z "$(ls $(echo "${mnt}/${PATTERN}"))" ]; then
+    # NO FILES, WE EXPORT
+    echo "Exporting..." >>/tmp/mountcopy.log
+    # Copy files fitting $PATTERN from the $DESTINATION to the root of the drive.
+    mv $(echo "${DESTINATION}/${PATTERN}") "$mnt/" 2>>/tmp/mountcopy.log || exit 105
+
+else
+    # FILES FOUND, WE IMPORT
+    echo "Importing..." >>/tmp/mountcopy.log
+    # Copy files fitting $PATTERN from the root of the drive to $DESTINATION.
+    cp $(echo "$mnt/$PATTERN") "$DESTINATION/" 2>>/tmp/mountcopy.log || exit 102
+fi
+
 # Unmount the drives filesystem
-umount "$mnt" || exit 103
+umount "$mnt" 2>>/tmp/mountcopy.log || exit 103
 # Remove temporary mount directory
-rmdir "$mnt" || exit 104
+rmdir "$mnt" 2>>/tmp/mountcopy.log || exit 104
